SELECT
    SYS_CONTEXT('USERENV', 'DB_NAME') AS base_de_donnees,
    SYS_CONTEXT('USERENV', 'CON_NAME') AS conteneur
FROM dual;
SELECT USER FROM dual;
SELECT table_name
FROM user_tables
WHERE table_name = 'DEBARQUEMENTS_POISSONS';
SELECT *
FROM DEBARQUEMENTS_POISSONS;
SELECT *
FROM debarquements_poissons;
SELECT *

FROM DEBARQUEMENTS_POISOONS;
SELECT COUNT(*) AS nombre_lignes
FROM DEBARQUEMENTS_POISOONS;
SELECT ID, COUNT(*) AS nombre
FROM DEBARQUEMENTS_POISOONS
GROUP BY ID
HAVING COUNT(*) > 1;
SELECT *
FROM DEBARQUEMENTS_POISOONS
WHERE ID IN (554, 543, 552, 553, 555, 547, 548)
ORDER BY ID;
SELECT ID, 
       MATRICULE, 
       POIDS_CREVETTES, 
       MATRICULE, 
       POIDS_CREVETTES, 
       VALEUR_CREVETTE, 
       POIDS_MERLU, 
       VALEUR_MERLU, 
       POIDS_AUTRES_ESPECES, 
       VALEUR_AUTRES_ESPECES, 
       COUNT(*) AS nombre 
FROM DEBARQUEMENTS_POISOONS 
GROUP BY ID, 
         MATRICULE, 
         POIDS_CREVETTES, 
         VALEUR_CREVETTE, 
         POIDS_MERLU, 
         VALEUR_MERLU, 
         POIDS_AUTRES_ESPECES, 
         VALEUR_AUTRES_ESPECES 
HAVING COUNT(*) > 1;, 
       VALEUR_CREVETTE, 
       POIDS_MERLU, 
       VALEUR_MERLU, 
       POIDS_AUTRES_ESPECES, 
       VALEUR_AUTRES_ESPECES, 
       COUNT(*) AS nombre 
FROM DEBARQUEMENTS_POISOONS 
GROUP BY ID, 
         MATRICULE, 
         POIDS_CREVETTES, 
         VALEUR_CREVETTE, 
         POIDS_MERLU, 
         VALEUR_MERLU, 
         POIDS_AUTRES_ESPECES, 
         VALEUR_AUTRES_ESPECES 
HAVING COUNT(*) > 1;
SELECT ID,
       MATRICULE,
       POIDS_CREVETTES,
       VALEUR_CREVETTE,
       POIDS_MERLU,
       VALEUR_MERLU,
       POIDS_AUTRES_ESPECES,
       VALEUR_AUTRES_ESPECES,
       COUNT(*) AS nombre
FROM DEBARQUEMENTS_POISOONS
GROUP BY ID,
         MATRICULE,
         POIDS_CREVETTES,
         VALEUR_CREVETTE,
         POIDS_MERLU,
         VALEUR_MERLU,
         POIDS_AUTRES_ESPECES,
         VALEUR_AUTRES_ESPECES
HAVING COUNT(*) > 1;
DESC DEBARQUEMENTS_POISOONS;
SELECT ID,
       MATRICULE,
       POIDS_CREVETTES,
       VALEUR_CREVETTE,
       POIDS_MERLU,
       VALEUR_MERLU,
       POIDS_AUTRESESPECES,
       VALEUR_AUTRESESPECES,
       COUNT(*) AS nombre
FROM DEBARQUEMENTS_POISOONS
GROUP BY ID,
         MATRICULE,
         POIDS_CREVETTES,
         VALEUR_CREVETTE,
         POIDS_MERLU,
         VALEUR_MERLU,
         POIDS_AUTRESESPECES,
         VALEUR_AUTRESESPECES
HAVING COUNT(*) > 1;
SELECT
    COUNT(*) AS TOTAL,
    SUM(CASE WHEN ID IS NULL THEN 1 ELSE 0 END) AS ID_MANQUANTS,
    SUM(CASE WHEN MATRICULE IS NULL THEN 1 ELSE 0 END) AS MATRICULE_MANQUANTS,
    SUM(CASE WHEN POIDS_CREVETTES IS NULL THEN 1 ELSE 0 END) AS POIDS_CREVETTES_MANQUANTS,
    SUM(CASE WHEN VALEUR_CREVETTE IS NULL THEN 1 ELSE 0 END) AS VALEUR_CREVETTE_MANQUANTS,
    SUM(CASE WHEN POIDS_MERLU IS NULL THEN 1 ELSE 0 END) AS POIDS_MERLU_MANQUANTS,
    SUM(CASE WHEN VALEUR_MERLU IS NULL THEN 1 ELSE 0 END) AS VALEUR_MERLU_MANQUANTS,
    SUM(CASE WHEN POIDS_AUTRESESPECES IS NULL THEN 1 ELSE 0 END) AS POIDS_AUTRESESPECES_MANQUANTS,
    SUM(CASE WHEN VALEUR_AUTRESESPECES IS NULL THEN 1 ELSE 0 END) AS VALEUR_AUTRESESPECES_MANQUANTS
FROM DEBARQUEMENTS_POISOONS;
SELECT *
FROM DEBARQUEMENTS_POISOONS
WHERE POIDS_MERLU IS NULL
   OR VALEUR_MERLU IS NULL
ORDER BY ID;
SELECT COUNT(*) AS lignes_sans_merlu
FROM DEBARQUEMENTS_POISOONS
WHERE POIDS_MERLU IS NULL
  AND VALEUR_MERLU IS NULL
  AND (
       POIDS_CREVETTES IS NOT NULL
       OR POIDS_AUTRESESPECES IS NOT NULL
      );
      DELETE FROM DEBARQUEMENTS_POISOONS
WHERE ROWID NOT IN (
    SELECT MIN(ROWID)
    FROM DEBARQUEMENTS_POISOONS
    GROUP BY ID
);
SELECT COUNT(*) AS nombre_lignes
FROM DEBARQUEMENTS_POISOONS;
SELECT ID, COUNT(*) AS nombre
FROM DEBARQUEMENTS_POISOONS
GROUP BY ID
HAVING COUNT(*) > 1;
SELECT *
FROM DEBARQUEMENTS_POISOONS
WHERE POIDS_MERLU IS NULL
   OR VALEUR_MERLU IS NULL
ORDER BY ID;
SELECT ID, COUNT(*) AS nombre
FROM DEBARQUEMENTS_POISOONS
GROUP BY ID
HAVING COUNT(*) > 1;
SELECT COUNT(*) AS lignes_sans_merlu
FROM DEBARQUEMENTS_POISOONS
WHERE POIDS_MERLU IS NULL
  AND VALEUR_MERLU IS NULL;
-- =====================================================
-- PROCEDURE PL/SQL : contrôle des débarquements
-- =====================================================

CREATE OR REPLACE PROCEDURE controler_debarquements
AS
    v_nombre NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_nombre
    FROM DEBARQUEMENTS_POISOONS;

    DBMS_OUTPUT.PUT_LINE(
        'Nombre de lignes dans DEBARQUEMENTS_POISOONS : '
        || v_nombre
    );
END;
/

SET SERVEROUTPUT ON;
EXEC controler_debarquements;